package za.co.lottoinsight

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import za.co.lottoinsight.data.DrawSync
import za.co.lottoinsight.data.LottoDatabase
import za.co.lottoinsight.export.ExportFiles
import za.co.lottoinsight.licence.LicenseGate
import za.co.lottoinsight.model.*

private val Yellow = Color(0xFFFFD339)
private val Background = Color(0xFF06173F)
private val Panel = Color(0xFF102A61)
private val Muted = Color(0xFFB8D7FA)
private val Green = Color(0xFF00CF86)
private val White = Color(0xFFF8FAFF)
private val lottoColorScheme = darkColorScheme(
    primary = Yellow, onPrimary = Background,
    secondary = Green, onSecondary = Background,
    background = Background, onBackground = White,
    surface = Panel, onSurface = White,
    surfaceVariant = Color(0xFF2B3037), onSurfaceVariant = Muted
)

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        val db = LottoDatabase(this)
        DrawSync.schedule(this)
        setContent {
            MaterialTheme(colorScheme = lottoColorScheme) {
                if (BuildConfig.LICENSE_REQUIRED) LicenseGate { LottoRoot(db) }
                else LottoRoot(db)
            }
        }
    }
}

@Composable
private fun LottoRoot(db: LottoDatabase) {
    val context = LocalContext.current
    val scope = rememberCoroutineScope()
    var tab by rememberSaveable { mutableIntStateOf(0) }
    var selectedId by rememberSaveable { mutableStateOf("lotto") }
    var strategy by rememberSaveable { mutableStateOf("Quick Pick") }
    var lineCount by rememberSaveable { mutableIntStateOf(5) }
    var drawList by remember { mutableStateOf(emptyList<Draw>()) }
    var saved by remember { mutableStateOf(emptyList<Ticket>()) }
    var generated by remember { mutableStateOf(emptyList<Ticket>()) }
    var neoNumbers by rememberSaveable { mutableStateOf(listOf(7, 14, 22, 28, 36, 41)) }
    var busy by remember { mutableStateOf(false) }
    var info by remember { mutableStateOf("Offline database ready") }
    val game = games.firstOrNull { it.id == selectedId } ?: games.first()

    fun reload() {
        scope.launch {
            val pair = withContext(Dispatchers.IO) { db.allDraws() to db.savedTickets() }
            drawList = pair.first
            saved = pair.second
        }
    }
    fun sync(force: Boolean) {
        if (busy) return
        scope.launch {
            busy = true
            try {
                val result = DrawSync.update(context, db, force)
                info = if (result > 0) "Source refreshed · $result records checked" else "Results checked recently"
            } catch (_: Exception) {
                info = "Offline · showing locally saved results"
            } finally {
                busy = false
                reload()
            }
        }
    }
    LaunchedEffect(Unit) {
        try {
            withContext(Dispatchers.IO) { db.loadBundledIfEmpty() }
            reload()
            sync(false)
        } catch (_: Exception) {
            info = "Database unavailable · retry later"
        }
    }

    val gameDraws = remember(drawList, selectedId) { drawList.filter { it.game == selectedId } }

    Scaffold(
        containerColor = Background,
        topBar = {
            if (tab != 0) Row(
                Modifier.fillMaxWidth().background(Background)
                    .padding(horizontal = 17.dp, vertical = 10.dp),
                verticalAlignment = Alignment.CenterVertically
            ) {
                Text("SA", color = White, fontWeight = FontWeight.Black, fontSize = 23.sp)
                Text("Lotto", color = Yellow, fontWeight = FontWeight.Black, fontSize = 23.sp)
                Spacer(Modifier.width(13.dp))
                Text(info, color = Muted, fontSize = 11.sp,
                    modifier = Modifier.weight(1f), maxLines = 1, overflow = TextOverflow.Ellipsis)
                TextButton(onClick = { sync(true) }, enabled = !busy) {
                    Text(if (busy) "Syncing" else "↻ Sync", color = Green)
                }
            }
        },
        bottomBar = {
            NeoBottomBar(tab) { target ->
                tab = target
                if (target == 0 || target == 1) selectedId = "lotto"
            }
        }
    ) { padding ->
        Box(Modifier.fillMaxSize().padding(padding)) {
            if (tab == 0) {
                NeoHome(
                    latest = drawList.firstOrNull { it.game == "lotto" },
                    selected = neoNumbers,
                    onSelectedChange = { value ->
                        neoNumbers = value.distinct().filter { it in 1..52 }.take(6).sorted()
                    },
                    onQuickPick = {
                        neoNumbers = NumberGenerator.generate(games.first(), 1, false)
                            .firstOrNull()?.numbers.orEmpty()
                    },
                    onSaveSelection = {
                        val valid = neoNumbers.distinct().sorted()
                        if (valid.size == 6 && valid.all { it in 1..52 }) {
                            scope.launch {
                                withContext(Dispatchers.IO) {
                                    db.saveTickets(listOf(Ticket(game = "lotto", numbers = valid)))
                                }
                                info = "Six Lotto numbers saved offline"
                                reload()
                                selectedId = "lotto"
                                tab = 4
                            }
                        }
                    },
                    onPlay = { selectedId = "lotto"; tab = 2 },
                    onResults = { selectedId = "lotto"; tab = 1 },
                    onMore = { tab = 5 },
                    onSync = { sync(true) }
                )
            } else if (tab == 5) {
                NeoMore(onAnalyse = { tab = 3 }, onSaved = { tab = 4 },
                    onSync = { sync(true) }, status = info)
            } else {
                Column(Modifier.fillMaxSize().background(Background)) {
                    LazyRow(
                        modifier = Modifier.fillMaxWidth(),
                        contentPadding = PaddingValues(horizontal = 14.dp, vertical = 8.dp),
                        horizontalArrangement = Arrangement.spacedBy(8.dp)
                    ) {
                        items(games, key = { it.id }) { option ->
                            FilterChip(
                                selected = game.id == option.id,
                                onClick = { selectedId = option.id; generated = emptyList() },
                                label = { Text(option.name, fontSize = 12.sp) },
                                colors = FilterChipDefaults.filterChipColors(
                                    selectedContainerColor = Yellow, selectedLabelColor = Background
                                )
                            )
                        }
                    }
                    when (tab) {
                        1 -> DrawScreen(game, gameDraws,
                            onPdf = {
                                ExportFiles.sharePdf(context, game.name + " Draw History",
                                    gameDraws.map { it.date + "  " + it.numbers.joinToString(" - ") +
                                        (it.bonus?.let { b -> "  + " + b } ?: "") })
                            },
                            onJpeg = {
                                ExportFiles.shareJpeg(context, game.name + " Draws",
                                    gameDraws.take(33).map { it.date + "  " + it.numbers.joinToString(" - ") })
                            })
                        2 -> GenerateScreen(
                            game = game, strategy = strategy, onStrategy = { strategy = it },
                            count = lineCount, onCount = { lineCount = it.coerceIn(1, 50) },
                            tickets = generated,
                            onGenerate = { generated = NumberGenerator.generate(game, lineCount, strategy == "Spread") },
                            onSave = {
                                if (generated.isNotEmpty()) {
                                    scope.launch {
                                        withContext(Dispatchers.IO) { db.saveTickets(generated) }
                                        info = generated.size.toString() + " lines saved offline"
                                        reload()
                                    }
                                }
                            },
                            onPdf = {
                                if (generated.isNotEmpty())
                                    ExportFiles.sharePdf(context, game.name + " Picks", generated.map(::ticketText))
                            },
                            onJpeg = {
                                if (generated.isNotEmpty())
                                    ExportFiles.shareJpeg(context, game.name + " Picks", generated.map(::ticketText))
                            })
                        3 -> AnalyzeScreen(game, gameDraws,
                            onPdf = { ExportFiles.sharePdf(context, game.name + " Frequencies", frequencyRows(gameDraws)) },
                            onJpeg = { ExportFiles.shareJpeg(context, game.name + " Frequencies", frequencyRows(gameDraws)) })
                        else -> SavedScreen(saved.filter { it.game == game.id },
                            onDelete = { id ->
                                scope.launch {
                                    withContext(Dispatchers.IO) { db.deleteTicket(id) }
                                    reload()
                                }
                            },
                            onPdf = {
                                ExportFiles.sharePdf(context, game.name + " Saved Picks",
                                    saved.filter { it.game == game.id }.map(::ticketText))
                            },
                            onJpeg = {
                                ExportFiles.shareJpeg(context, game.name + " Saved Picks",
                                    saved.filter { it.game == game.id }.map(::ticketText))
                            })
                    }
                }
            }
        }
    }
}

private fun ticketText(ticket: Ticket): String =
    ticket.numbers.joinToString(" - ") { it.toString().padStart(2, '0') } +
        (ticket.powerBall?.let { "  PB: ${it.toString().padStart(2, '0')}" } ?: "")

private fun frequencyRows(draws: List<Draw>): List<String> =
    draws.flatMap { it.numbers }
        .groupingBy { it }.eachCount()
        .entries.sortedWith(compareByDescending<Map.Entry<Int, Int>> { it.value }.thenBy { it.key })
        .map { "Number ${it.key.toString().padStart(2, '0')}  ·  ${it.value} appearances" }

@Composable
private fun Heading(title: String, subtitle: String) {
    Column(Modifier.padding(bottom = 14.dp)) {
        Text(title, fontSize = 25.sp, fontWeight = FontWeight.ExtraBold)
        Text(subtitle, fontSize = 12.sp, color = Muted)
    }
}

@Composable
private fun LottoPanel(modifier: Modifier = Modifier, content: @Composable ColumnScope.() -> Unit) {
    Card(
        modifier = modifier,
        colors = CardDefaults.cardColors(containerColor = Panel),
        shape = RoundedCornerShape(20.dp)
    ) { Column(Modifier.fillMaxWidth().padding(16.dp), content = content) }
}

@Composable
private fun Balls(numbers: List<Int>, bonus: Int? = null, isPower: Boolean = false) {
    Row(horizontalArrangement = Arrangement.spacedBy(6.dp), verticalAlignment = Alignment.CenterVertically) {
        numbers.forEach { n ->
            Box(
                Modifier.size(37.dp).background(Yellow, CircleShape),
                contentAlignment = Alignment.Center
            ) {
                Text(n.toString().padStart(2, '0'), color = Background, fontWeight = FontWeight.Bold, fontSize = 13.sp)
            }
        }
        if (bonus != null) {
            Box(
                Modifier.size(37.dp).background(if (isPower) Color(0xFFEA4550) else Color(0xFF6A7180), CircleShape),
                contentAlignment = Alignment.Center
            ) {
                Text(bonus.toString().padStart(2, '0'), color = Color.White, fontWeight = FontWeight.Bold, fontSize = 13.sp)
            }
        }
    }
}

@Composable
private fun HomeScreen(
    game: LottoGame, draws: List<Draw>, latest: Draw?,
    toGenerate: () -> Unit, toHistory: () -> Unit, toAnalysis: () -> Unit
) {
    LazyColumn(
        modifier = Modifier.fillMaxSize(),
        contentPadding = PaddingValues(16.dp),
        verticalArrangement = Arrangement.spacedBy(14.dp)
    ) {
        item {
            Heading("Your numbers, smarter.", "Explore past results and plan combinations")
            LottoPanel {
                Text("LATEST ${game.name.uppercase()} RESULT", color = Yellow, fontSize = 11.sp, fontWeight = FontWeight.Bold)
                Spacer(Modifier.height(7.dp))
                Text(latest?.date ?: "No results stored yet", fontSize = 13.sp, color = Muted)
                Spacer(Modifier.height(18.dp))
                if (latest != null) {
                    Balls(latest.numbers, latest.bonus, game.powerBallMax > 0)
                    Spacer(Modifier.height(11.dp))
                    Text(
                        if (latest.verified) "Source-marked verified · confirm with operator"
                        else "Source unverified · confirm with operator",
                        color = Muted, fontSize = 11.sp
                    )
                } else Text("Connect to the internet to import draw history.", color = Muted)
            }
        }
        item {
            Card(
                modifier = Modifier.fillMaxWidth().clickable(onClick = toGenerate),
                colors = CardDefaults.cardColors(containerColor = Yellow),
                shape = RoundedCornerShape(20.dp)
            ) {
                Column(Modifier.padding(22.dp)) {
                    Text("GENERATE YOUR PICKS", color = Background, fontSize = 21.sp, fontWeight = FontWeight.Black)
                    Spacer(Modifier.height(7.dp))
                    Text("Unique number lines in one tap  →", color = Background, fontSize = 13.sp)
                }
            }
        }
        item {
            Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                LottoPanel(Modifier.weight(1f).clickable(onClick = toHistory)) {
                    Text("${draws.size}", fontSize = 28.sp, color = Yellow, fontWeight = FontWeight.Bold)
                    Text("Stored draws", color = Muted, fontSize = 12.sp)
                }
                LottoPanel(Modifier.weight(1f).clickable(onClick = toAnalysis)) {
                    Text("${draws.flatMap { it.numbers }.distinct().size}", fontSize = 28.sp, color = Green, fontWeight = FontWeight.Bold)
                    Text("Numbers observed", color = Muted, fontSize = 12.sp)
                }
            }
        }
        item { InfoNotice() }
    }
}

@Composable
private fun InfoNotice() {
    LottoPanel {
        Text("OFFLINE • 18+ • RESPONSIBLE PLAY", color = Yellow, fontSize = 11.sp, fontWeight = FontWeight.Bold)
        Spacer(Modifier.height(7.dp))
        Text(
            "Saved draws and tools work without data. Historical numbers do not predict future random results. " +
                "Data: BetTip (bettip.co.za). Verify wins with the official lottery operator.",
            color = Muted, fontSize = 12.sp
        )
        Spacer(Modifier.height(8.dp))
        Text("Gambling helpline: 0800 006 008", color = Muted, fontSize = 11.sp)
    }
}

@Composable
private fun DrawScreen(game: LottoGame, draws: List<Draw>, onPdf: () -> Unit, onJpeg: () -> Unit) {
    var query by remember(game.id) { mutableStateOf("") }
    val shown = remember(draws, query) {
        draws.filter { query.isBlank() || it.date.contains(query.trim()) }.take(300)
    }
    LazyColumn(
        modifier = Modifier.fillMaxSize(),
        contentPadding = PaddingValues(16.dp),
        verticalArrangement = Arrangement.spacedBy(12.dp)
    ) {
        item {
            Heading("Draw archive", "${draws.size} offline ${game.name} results")
            OutlinedTextField(
                value = query, onValueChange = { query = it.take(12) },
                label = { Text("Search date (YYYY-MM-DD)") },
                modifier = Modifier.fillMaxWidth(), singleLine = true
            )
            Spacer(Modifier.height(10.dp))
            ExportButtons(onPdf, onJpeg, draws.isNotEmpty())
        }
        items(shown, key = { "${it.game}_${it.date}" }) { draw ->
            LottoPanel {
                Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                    Text(draw.date, fontWeight = FontWeight.Bold)
                    Text(if (draw.verified) "Source verified" else "Unverified", color = Muted, fontSize = 11.sp)
                }
                Spacer(Modifier.height(14.dp))
                Balls(draw.numbers, draw.bonus, game.powerBallMax > 0)
            }
        }
        if (shown.isEmpty()) item { Text("No matching results stored.", color = Muted) }
        item { Text("Displaying up to 300 rows; PDF exports all stored rows.", color = Muted, fontSize = 11.sp) }
    }
}

@Composable
private fun GenerateScreen(
    game: LottoGame, strategy: String, onStrategy: (String) -> Unit,
    count: Int, onCount: (Int) -> Unit, tickets: List<Ticket>,
    onGenerate: () -> Unit, onSave: () -> Unit,
    onPdf: () -> Unit, onJpeg: () -> Unit
) {
    LazyColumn(
        modifier = Modifier.fillMaxSize(),
        contentPadding = PaddingValues(16.dp),
        verticalArrangement = Arrangement.spacedBy(13.dp)
    ) {
        item {
            Heading("Number generator", "Create up to 50 unique number lines")
            LottoPanel {
                Text("SELECTION METHOD", color = Muted, fontSize = 11.sp, fontWeight = FontWeight.Bold)
                Spacer(Modifier.height(8.dp))
                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    listOf("Quick Pick", "Spread").forEach { option ->
                        FilterChip(
                            selected = strategy == option, onClick = { onStrategy(option) },
                            label = { Text(option) },
                            colors = FilterChipDefaults.filterChipColors(
                                selectedContainerColor = Yellow, selectedLabelColor = Background
                            )
                        )
                    }
                }
                Text(
                    if (strategy == "Quick Pick") "Uniform random selections."
                    else "One random number from each range segment. This changes selection patterns, not draw odds.",
                    fontSize = 12.sp, color = Muted
                )
                Spacer(Modifier.height(16.dp))
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Text("Number of lines", modifier = Modifier.weight(1f), fontWeight = FontWeight.Medium)
                    OutlinedButton(onClick = { onCount(count - 1) }, enabled = count > 1) { Text("−") }
                    Text(" $count ", fontWeight = FontWeight.Bold, fontSize = 18.sp)
                    OutlinedButton(onClick = { onCount(count + 1) }, enabled = count < 50) { Text("+") }
                }
                Spacer(Modifier.height(13.dp))
                Button(onClick = onGenerate, modifier = Modifier.fillMaxWidth()) {
                    Text("✦ Generate ${game.name} Lines", fontWeight = FontWeight.Bold)
                }
            }
        }
        if (tickets.isNotEmpty()) item {
            LottoPanel {
                Row(Modifier.fillMaxWidth(), verticalAlignment = Alignment.CenterVertically) {
                    Text("${tickets.size} GENERATED LINES", fontWeight = FontWeight.Bold, color = Yellow, modifier = Modifier.weight(1f))
                    TextButton(onClick = onSave) { Text("Save all") }
                }
                Spacer(Modifier.height(5.dp))
                ExportButtons(onPdf, onJpeg, true)
            }
        }
        items(tickets) { ticket ->
            LottoPanel {
                Text("LINE ${tickets.indexOf(ticket) + 1}", color = Muted, fontSize = 11.sp)
                Spacer(Modifier.height(9.dp))
                Balls(ticket.numbers, ticket.powerBall, game.powerBallMax > 0)
            }
        }
        if (tickets.isEmpty()) item { Text("Select a method and tap Generate to create your first lines.", color = Muted) }
        item { Text("Unofficial suggestions, not purchased lottery tickets. Every valid line has the same draw probability.", color = Muted, fontSize = 11.sp) }
    }
}

@Composable
private fun AnalyzeScreen(game: LottoGame, draws: List<Draw>, onPdf: () -> Unit, onJpeg: () -> Unit) {
    val counts = remember(draws) {
        draws.flatMap { it.numbers }.groupingBy { it }.eachCount()
    }
    val ranked = counts.entries.sortedWith(compareByDescending<Map.Entry<Int, Int>> { it.value }.thenBy { it.key })
    val peak = ranked.firstOrNull()?.value ?: 1
    LazyColumn(
        modifier = Modifier.fillMaxSize(),
        contentPadding = PaddingValues(16.dp),
        verticalArrangement = Arrangement.spacedBy(10.dp)
    ) {
        item {
            Heading("Number analytics", "Historical frequencies, not predictions")
            LottoPanel {
                Text("${draws.size} draws analysed", color = Yellow, fontSize = 23.sp, fontWeight = FontWeight.Bold)
                Text("Historic game rules and number ranges changed over time.", color = Muted, fontSize = 12.sp)
                Spacer(Modifier.height(9.dp))
                ExportButtons(onPdf, onJpeg, ranked.isNotEmpty())
            }
        }
        items(ranked.take(30)) { entry ->
            LottoPanel {
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Box(
                        Modifier.size(39.dp).background(Yellow, CircleShape),
                        contentAlignment = Alignment.Center
                    ) {
                        Text(entry.key.toString().padStart(2,'0'), fontWeight = FontWeight.Bold, color = Background)
                    }
                    Spacer(Modifier.width(12.dp))
                    Column(Modifier.weight(1f)) {
                        Text("${entry.value} historical appearances", fontWeight = FontWeight.Medium, fontSize = 13.sp)
                        Spacer(Modifier.height(8.dp))
                        Box(Modifier.fillMaxWidth().height(6.dp).background(Color(0xFF353B42), CircleShape)) {
                            Box(Modifier.fillMaxWidth(entry.value.toFloat() / peak).height(6.dp).background(Green, CircleShape))
                        }
                    }
                }
            }
        }
        if (ranked.isEmpty()) item { Text("No historical data is currently available for ${game.name}.", color = Muted) }
        item { InfoNotice() }
    }
}

@Composable
private fun SavedScreen(tickets: List<Ticket>, onDelete: (Long) -> Unit, onPdf: () -> Unit, onJpeg: () -> Unit) {
    LazyColumn(
        modifier = Modifier.fillMaxSize(),
        contentPadding = PaddingValues(16.dp),
        verticalArrangement = Arrangement.spacedBy(12.dp)
    ) {
        item {
            Heading("Saved number lines", "Stored privately on this device")
            ExportButtons(onPdf, onJpeg, tickets.isNotEmpty())
        }
        items(tickets, key = { it.id }) { ticket ->
            LottoPanel {
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Text(ticket.created, modifier = Modifier.weight(1f), color = Muted, fontSize = 12.sp)
                    TextButton(onClick = { onDelete(ticket.id) }) { Text("Delete") }
                }
                Balls(ticket.numbers, ticket.powerBall, ticket.game.startsWith("powerball"))
            }
        }
        if (tickets.isEmpty()) item {
            Text("No saved lines for this game. Generate some and tap Save all.", color = Muted)
        }
        item { Text("Saved lines do not represent purchased entries.", color = Muted, fontSize = 11.sp) }
    }
}

@Composable
private fun ExportButtons(onPdf: () -> Unit, onJpeg: () -> Unit, enabled: Boolean) {
    Row(horizontalArrangement = Arrangement.spacedBy(10.dp)) {
        OutlinedButton(onClick = onPdf, enabled = enabled, modifier = Modifier.weight(1f)) { Text("↓ PDF") }
        OutlinedButton(onClick = onJpeg, enabled = enabled, modifier = Modifier.weight(1f)) { Text("↓ JPEG") }
    }
}
